### ISSUE TITLE
FR1.  Login Page with Google account 

### ISSUE THREAD

**Issue by gh4683** [WSU-4110/CarpoolingApp#1]
|FR1.  Login Page with Google account 
|---|
|**Goal**: The system will greet the user with a login page where there will be able to login using a Google account through Google Oauth2
**Stakeholders:** All|
| **Description:** When a user opens the app, they will be greeted with a login screen. The login credentials would be a Google account and would be authenticated using Google Oauth2, which allows Google to handle logging in and security with the Google account as a provided API.   |
| **Origin:** Based on initial project specification   document, team members came up with this description during the first   meeting.|
| **Version:** 1.0  |  
|**Date:** 01/26/2020 
|  **Priority:** 1 |

**Comment by nidhi-nadig10** [comment]
Login page no longer uses google- just token connected to api
