### ISSUE TITLE
FR13. Pick order of passengers 

### ISSUE THREAD

**Issue by gh4683** [WSU-4110/CarpoolingApp#13]
|FR13. Pick order of passengers |
|---|
|**Goal**: The driver picks which order he/she wants to pick up passengers on the app
**Stakeholders:** Drivers|
| **Description:** Once the driver and passengers are matched, the driver is given the locations of the passengers he needs to pick up. At his/her own discretion, the driver can set the order that they wish to pick up the passengers. Once the order is set in the app, the passengers receive a notification saying where they are in the order to be prepared for pick-up.  |
| **Origin:** Based on initial project specification document, team members came up with this description during the first meeting.|
| **Version:** 1.0  |  
|**Date:** 01/26/2020 
|  **Priority:** 1 |

**Comment by nidhi-nadig10** [comment]
order can't be picked anymore- its assigned by the app
