### ISSUE TITLE
NR2. Security – App will be secured through Google Oauth2 

### ISSUE THREAD

**Issue by gh4683** [WSU-4110/CarpoolingApp#17]
|NR2. Security – App will be secured through Google Oauth2 
|---|
|**Goal**: The apps users will be verified through Oauth2 
**Stakeholders:** All|
| **Description:** This will verify the identity of the users to make the app safer and allow authentication to be done under a third party which makes sure that as administrators, we also cannot see user data.  |
| **Version:** 1.0  |  
|**Date:** 01/26/2020 
|  **Priority:** 1 |

**Comment by nidhi-nadig10** [comment]
Changed to user's being assigned a token on login to authorize them
