### ISSUE TITLE
Prevent buttons from being pressable when fields aren't filled in

### ISSUE THREAD

**Issue by cj5100** [WSU-4110/CarpoolingApp#48]
An easy way to perform proper form validation is to prevent users from moving on when certain fields aren't filled in. In most screens right now, I can have empty fields and still move on. The button should be slightly greyed out and unpressable until the form is in a proper state.

**Comment by darpanshah-wsu** [comment]
Fields turn red when if not field when pressing button, will not allow user to move on until fields are filled
